name: pixelconquest
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flame: ^1.12.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.7
  flutter_riverpod: ^2.4.9
  supabase_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  #background_image: assets/images/loading_background.png
  color: "#000000"
  image: assets/images/loading_logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
